### ISSUE TITLE
compile error in os openEuler 2403sp1

### ISSUE THREAD

**Issue by Icedroid** [deepseek-ai/3FS#151]
OS: openEuler 2403sp1
ARCH: X86_64
Clang version: 
```
# clang --version
clang version 17.0.6 ( 17.0.6-30.oe2403sp1)
Target: x86_64-openEuler-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

# clang++ --version
clang version 17.0.6 ( 17.0.6-30.oe2403sp1)
Target: x86_64-openEuler-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

```

```
# cmake -S . -B build -DCMAKE_CXX_COMPILER=clang++-14 -DCMAKE_C_COMPILER=clang-14 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
# cmake --build build -j 32
[ 33%] Building CXX object third_party/rocksdb/CMakeFiles/rocksdb.dir/file/readahead_raf.cc.o
cd /root/3FS/build/third_party/rocksdb && /usr/bin/clang++-14 -DGFLAGS=1 -DGFLAGS_IS_A_DLL=0 -DHAVE_PCLMUL -DHAVE_SSE42 -DLZ4 -DOS_LINUX -DROCKSDB_FALLOCATE_PRESENT -DROCKSDB_LIB_IO_POSIX -DROCKSDB_MALLOC_USABLE_SIZE -DROCKSDB_NAMESPACE=rocksdb_internal -DROCKSDB_NO_DYNAMIC_EXTENSION -DROCKSDB_PLATFORM_POSIX -DROCKSDB_PTHREAD_ADAPTIVE_MUTEX -DROCKSDB_RANGESYNC_PRESENT -DROCKSDB_SCHED_GETCPU_PRESENT -DZSTD -I//include -I/root/3FS/third_party/rocksdb -I/root/3FS/third_party/rocksdb/include -isystem /root/3FS/third_party/zstd/lib -W -Wextra -Wall -pthread -Wsign-compare -Wshadow -Wno-unused-parameter -Woverloaded-virtual -Wnon-virtual-dtor -Wno-missing-field-initializers -Wno-strict-aliasing -Wno-invalid-offsetof -fno-omit-frame-pointer -momit-leaf-frame-pointer -march=native -Werror -O2 -g -DNDEBUG -std=c++20 -fPIC -fmacro-prefix-map=/root/3FS=. -msse4.2 -mavx2 -MD -MT third_party/rocksdb/CMakeFiles/rocksdb.dir/file/readahead_raf.cc.o -MF CMakeFiles/rocksdb.dir/file/readahead_raf.cc.o.d -o CMakeFiles/rocksdb.dir/file/readahead_raf.cc.o -c /root/3FS/third_party/rocksdb/file/readahead_raf.cc
/root/3FS/third_party/rocksdb/cache/lru_cache.cc:94:12: error: variable 'count' set but not used [-Werror,-Wunused-but-set-variable]
   94 |   uint32_t count = 0;
      |            ^
[ 33%] Building CXX object third_party/rocksdb/CMakeFiles/rocksdb.dir/file/sequence_file_reader.cc.o
cd /root/3FS/build/third_party/rocksdb && /usr/bin/clang++-14 -DGFLAGS=1 -DGFLAGS_IS_A_DLL=0 -DHAVE_PCLMUL -DHAVE_SSE42 -DLZ4 -DOS_LINUX -DROCKSDB_FALLOCATE_PRESENT -DROCKSDB_LIB_IO_POSIX -DROCKSDB_MALLOC_USABLE_SIZE -DROCKSDB_NAMESPACE=rocksdb_internal -DROCKSDB_NO_DYNAMIC_EXTENSION -DROCKSDB_PLATFORM_POSIX -DROCKSDB_PTHREAD_ADAPTIVE_MUTEX -DROCKSDB_RANGESYNC_PRESENT -DROCKSDB_SCHED_GETCPU_PRESENT -DZSTD -I//include -I/root/3FS/third_party/rocksdb -I/root/3FS/third_party/rocksdb/include -isystem /root/3FS/third_party/zstd/lib -W -Wextra -Wall -pthread -Wsign-compare -Wshadow -Wno-unused-parameter -Woverloaded-virtual -Wnon-virtual-dtor -Wno-missing-field-initializers -Wno-strict-aliasing -Wno-invalid-offsetof -fno-omit-frame-pointer -momit-leaf-frame-pointer -march=native -Werror -O2 -g -DNDEBUG -std=c++20 -fPIC -fmacro-prefix-map=/root/3FS=. -msse4.2 -mavx2 -MD -MT third_party/rocksdb/CMakeFiles/rocksdb.dir/file/sequence_file_reader.cc.o -MF CMakeFiles/rocksdb.dir/file/sequence_file_reader.cc.o.d -o CMakeFiles/rocksdb.dir/file/sequence_file_reader.cc.o -c /root/3FS/third_party/rocksdb/file/sequence_file_reader.cc
1 error generated.
gmake[2]: *** [third_party/rocksdb/CMakeFiles/rocksdb.dir/build.make:188: third_party/rocksdb/CMakeFiles/rocksdb.dir/cache/lru_cache.cc.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
/root/3FS/third_party/rocksdb/db/version_edit_handler.cc:29:10: error: variable 'recovered_edits' set but not used [-Werror,-Wunused-but-set-variable]
   29 |   size_t recovered_edits = 0;
      |          ^
1 error generated.
gmake[2]: *** [third_party/rocksdb/CMakeFiles/rocksdb.dir/build.make:1266: third_party/rocksdb/CMakeFiles/rocksdb.dir/db/version_edit_handler.cc.o] Error 1
gmake[2]: Leaving directory '/root/3FS/build'
gmake[1]: *** [CMakeFiles/Makefile2:2712: third_party/rocksdb/CMakeFiles/rocksdb.dir/all] Error 2
gmake[1]: Leaving directory '/root/3FS/build'
gmake: *** [Makefile:146: all] Error 2

```

**Comment by yuchengkang** [comment]
Just turn to clang 14

**Comment by bugwz** [comment]
you can remove `clang` and `llvm`, then install `clang+llvm-14`, such as: 

```bash
dnf remove clang llvm

mkdir -p /tmp/clang
cd /tmp/clang
wget https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.6/clang+llvm-14.0.6-x86_64-linux-gnu-rhel-8.4.tar.xz
tar -xf clang+llvm-14.0.6-x86_64-linux-gnu-rhel-8.4.tar.xz
mv clang+llvm-14.0.6-x86_64-linux-gnu-rhel-8.4 /usr/local/clang-llvm-14
ln -s /usr/local/clang-llvm-14/bin/clang++ /usr/local/clang-llvm-14/bin/clang++-14
ln -s /usr/local/clang-llvm-14/bin/clang-format /usr/local/clang-llvm-14/bin/clang-format-14
ln -s /usr/local/clang-llvm-14/bin/clang-tidy /usr/local/clang-llvm-14/bin/clang-tidy-14
ln -s /usr/local/clang-llvm-14/bin/clang-format /usr/bin/clang-format-14
echo "export PATH=\$PATH:/usr/local/clang-llvm-14/bin" >> /root/.bashrc
cd /
rm -rf /tmp/clang
```

it runs well on centos 9 stream. @Icedroid

**Comment by Icedroid** [comment]
@bugwz 

I install clang with your command, also meet the same error as follow:

```
# /usr/local/clang-llvm-14/bin/clang-14 --version
clang version 14.0.6 (https://github.com/llvm/llvm-project.git f28c006a5895fc0e329fe15fead81e37457cb1d1)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/clang-llvm-14/bin

# cmake -S . -B build -DCMAKE_CXX_COMPILER=clang++-14 -DCMAKE_C_COMPILER=clang-14 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
-- The C compiler identification is Clang 14.0.6
-- The CXX compiler identification is Clang 14.0.6
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /usr/local/clang-llvm-14/bin/clang-14
-- Check for working C compiler: /usr/local/clang-llvm-14/bin/clang-14 - broken
CMake Error at /usr/share/cmake/Modules/CMakeTestCCompiler.cmake:67 (message):
  The C compiler

    "/usr/local/clang-llvm-14/bin/clang-14"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: '/root/3FS/build/CMakeFiles/CMakeScratch/TryCompile-6yebke'

    Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_31aae/fast
    /usr/bin/gmake  -f CMakeFiles/cmTC_31aae.dir/build.make CMakeFiles/cmTC_31aae.dir/build
    gmake[1]: Entering directory '/root/3FS/build/CMakeFiles/CMakeScratch/TryCompile-6yebke'
    Building C object CMakeFiles/cmTC_31aae.dir/testCCompiler.c.o
    /usr/local/clang-llvm-14/bin/clang-14    -MD -MT CMakeFiles/cmTC_31aae.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_31aae.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_31aae.dir/testCCompiler.c.o -c /root/3FS/build/CMakeFiles/CMakeScratch/TryCompile-6yebke/testCCompiler.c
    Linking C executable cmTC_31aae
    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_31aae.dir/link.txt --verbose=1
    /usr/local/clang-llvm-14/bin/clang-14 CMakeFiles/cmTC_31aae.dir/testCCompiler.c.o -o cmTC_31aae
    /usr/bin/ld: cannot find crtbegin.o: No such file or directory
    /usr/bin/ld: cannot find -lgcc: No such file or directory
    /usr/bin/ld: cannot find -lgcc_s: No such file or directory
    clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
    gmake[1]: *** [CMakeFiles/cmTC_31aae.dir/build.make:100: cmTC_31aae] Error 1
    gmake[1]: Leaving directory '/root/3FS/build/CMakeFiles/CMakeScratch/TryCompile-6yebke'
    gmake: *** [Makefile:127: cmTC_31aae/fast] Error 2





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


-- Configuring incomplete, errors occurred!


```

**Comment by Icedroid** [comment]
I try to compile with ubuntu 22.04. It give errors to me

![Image](https://github.com/user-attachments/assets/90053073-c14d-4e2a-833c-4af0ba81f3b4)

**Comment by bugwz** [comment]
I don't have an OpenEuler environment, so I can't provide precise solutions for OpenEuler. You can ask DeepSeek. And, if you want to compile on ubuntu 22.04, you can use this dockerfile, which I have tested and works well.

https://github.com/deepseek-ai/3FS/blob/main/dockerfile/dev.dockerfile

@Icedroid

**Comment by Icedroid** [comment]
I use docker ubuntu 22.04 to run mgmtd_main , but I got these error. cloud you help me ?  I has already install 

`apt install -y rdma-core ibverbs-utils perftest ibutils infiniband-diags 
`
How to know mgmtd_main run successfully? @bugwz 

![Image](https://github.com/user-attachments/assets/c7e68e14-95aa-40e3-940a-87f4ca3357a4)

**Comment by bugwz** [comment]
@Icedroid Sorry, I'm also just a storage enthusiast, not a 3fs member. I don't known about this issue, maybe u can create an issue ~😀

**Comment by qiuxinyidian** [comment]
do you build  3FS sucess on openeuler 24.03 SP1? i get such error like bellow:
`3FS/src/common/net/Listener.cc:95:17: error: no matching constructor for initialization of 'folly::coro::ServerSocket'   95 |       co_return folly::coro::ServerSocket(folly::AsyncServerSocket::newSocket(evb),`

3fs call folly fun error,but the code modify at 2025-07-27
